### ISSUE TITLE
channel used for France

### ISSUE THREAD

**Issue by Marc-marc-marc** [iandees/supybot-plugin-osm#28]
Hello,
Could you change the channel used for France from #osm-fr to #osm-fr-annonce and add the notification of notes.
Regards,
Marc

**Comment by Marc-marc-marc** [comment]
@iandees Thanks but osmbot-test is still on the old channel and quiet

**Comment by iandees** [comment]
I forgot to have the bot join the channel. I just did that and it should be OK now. Let me know if you still don't see anything.

**Comment by iandees** [comment]
Looks like the note checking code was stalled. I gave it a nudge and it's running again.
