### ISSUE TITLE
No more notes showing up for Norway

### ISSUE THREAD

**Issue by FredrikLindseth** [iandees/supybot-plugin-osm#31]
Hi,
The osmbot-test is still present in #osm-no and is notifying us for new users, but for some reason the bot doesn't notify us for new notes anymore.

This was added in https://github.com/iandees/supybot-plugin-osm/commit/b11b6c5c2f0a0172c0cbfdbf8eb379eaefa97644#diff-66c71ea3faaa52c277917c951aa67921R179 and did work for a long time

Has something changed on your end?

**Comment by Marc-marc-marc** [comment]
same issue in #osm-fr-annonce, last one 2019-07-16

**Comment by iandees** [comment]
The bot stopped running … I will look into fixing it when I get back in front of a computer.

**Comment by FredrikLindseth** [comment]
The notes are back. Thanks 🥇
